version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: FUT_backend_php_apache
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: FUT_backend_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: FUT_backend_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306" 
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: FUT_backend_phpmyadmin
    environment:
      PMA_HOST: db 
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8081:80" 
    depends_on:
      - db

volumes:
  db-data: