INSERT INTO
    `Nationalities`
VALUES (
        NULL,
        'Algerian',
        'https://www.worldometers.info/img/flags/small/tn_ag-flag.gif'
    ),
    (
        NULL,
        'German',
        'https://www.worldometers.info/img/flags/small/tn_gm-flag.gif'
    ),
    (
        NULL,
        'Argentine',
        'https://www.worldometers.info/img/flags/small/tn_ar-flag.gif'
    ),
    (
        NULL,
        'Belgian',
        'https://www.worldometers.info/img/flags/small/tn_be-flag.gif'
    ),
    (
        NULL,
        'Brazilian',
        'https://www.worldometers.info/img/flags/small/tn_br-flag.gif'
    ),
    (
        NULL,
        'Dutch',
        'https://www.worldometers.info/img/flags/small/tn_nl-flag.gif'
    ),
    (
        NULL,
        'Egyptian',
        'https://www.worldometers.info/img/flags/small/tn_eg-flag.gif'
    ),
    (
        NULL,
        'French',
        'https://www.worldometers.info/img/flags/small/tn_fr-flag.gif'
    ),
    (
        NULL,
        'Italian',
        'https://www.worldometers.info/img/flags/small/tn_it-flag.gif'
    ),
    (
        NULL,
        'Japanese',
        'https://www.worldometers.info/img/flags/small/tn_ja-flag.gif'
    ),
    (
        NULL,
        'Moroccan',
        'https://www.worldometers.info/img/flags/small/tn_mo-flag.gif'
    ),
    (
        NULL,
        'Mexican',
        'https://www.worldometers.info/img/flags/small/tn_mx-flag.gif'
    ),
    (
        NULL,
        'Nigerian',
        'https://www.worldometers.info/img/flags/small/tn_ni-flag.gif'
    ),
    (
        NULL,
        'Portuguese',
        'https://www.worldometers.info/img/flags/small/tn_po-flag.gif'
    ),
    (
        NULL,
        'Spanish',
        'https://www.worldometers.info/img/flags/small/tn_sp-flag.gif'
    ),
    (
        NULL,
        'Swedish',
        'https://www.worldometers.info/img/flags/small/tn_sw-flag.gif'
    );

-- SELECT * FROM `Nationalities`;
INSERT INTO
    `Clubs`
VALUES (
        NULL,
        "Manchester United",
        "https://cdn.sofifa.net/meta/team/14/60.png"
    ),
    (
        NULL,
        "Chelsea",
        "https://cdn.sofifa.net/meta/team/18/60.png"
    ),
    (
        NULL,
        "Arsenal",
        "https://cdn.sofifa.net/meta/team/19/60.png"
    ),
    (
        NULL,
        "Inter",
        "https://cdn.sofifa.net/meta/team/2930/60.png"
    ),
    (
        NULL,
        "FC Barcelona",
        "https://cdn.sofifa.net/meta/team/83/60.png"
    ),
    (
        NULL,
        "Paris Saint Germain",
        "https://cdn.sofifa.net/meta/team/591/60.png"
    ),
    (
        NULL,
        "Roma",
        "https://cdn.sofifa.net/meta/team/37/60.png"
    ),
    (
        NULL,
        "Real Madrid",
        "https://cdn.sofifa.net/meta/team/3468/60.png"
    ),
    (
        NULL,
        "Liverpool",
        "https://cdn.sofifa.net/meta/team/8/60.png"
    ),
    (
        NULL,
        "Juventus",
        "https://cdn.sofifa.net/meta/team/625/60.png"
    ),
    (
        NULL,
        "Manchester City",
        "https://cdn.sofifa.net/meta/team/9/60.png"
    ),
    (
        NULL,
        "FC Bayern München",
        "https://cdn.sofifa.net/meta/team/503/60.png"
    ),
    (
        NULL,
        "Tottenham Hotspur",
        "https://cdn.sofifa.net/meta/team/6/60.png"
    ),
    (
        NULL,
        "Atalanta",
        "https://cdn.sofifa.net/meta/team/708/60.png"
    ),
    (
        NULL,
        "Aston Villa",
        "https://cdn.sofifa.net/meta/team/15/60.png"
    ),
    (
        NULL,
        "Olympique de Marseille",
        "https://cdn.sofifa.net/meta/team/44/60.png"
    ),
    (
        NULL,
        "Brighton & Hove Albion",
        "https://cdn.sofifa.net/meta/team/78/60.png"
    ),
    (
        NULL,
        "Bayer 04 Leverkusen",
        "https://cdn.sofifa.net/meta/team/3321/60.png"
    ),
    (
        NULL,
        "Milan",
        "https://cdn.sofifa.net/meta/team/113/60.png"
    ),
    (
        NULL,
        "Borussia Dortmund",
        "https://cdn.sofifa.net/meta/team/68/60.png"
    ),
    (
        NULL,
        "Atlético Madrid",
        "https://cdn.sofifa.net/meta/team/7980/60.png"
    ),
    (
        NULL,
        "Napoli",
        "https://cdn.sofifa.net/meta/team/597/60.png"
    ),
    (
        NULL,
        "Galatasaray",
        "https://cdn.sofifa.net/meta/team/34/60.png"
    ),
    (
        NULL,
        "Ajax",
        "https://cdn.sofifa.net/meta/team/629/60.png"
    );

INSERT INTO
    `Detail_GKs`
VALUES
    -- DONNA
    (NULL, 90, 84, 73, 90, 52, 87),
    -- ALISON
    (NULL, 86, 86, 85, 89, 56, 90),
    --    courtois
    (NULL, 85, 89, 76, 90, 46, 88),
    --    Stegen
    (NULL, 86, 58, 89, 91, 47, 86);

INSERT INTO
    Detail_players
VALUES (NULL, 97, 90, 80, 92, 36, 78),
    (NULL, 66, 80, 86, 84, 87, 85),
    (NULL, 81, 86, 86, 91, 77, 75),
    (NULL, 88, 92, 70, 81, 45, 88),
    (NULL, 80, 87, 83, 88, 78, 83),
    (NULL, 82, 89, 90, 91, 72, 78),
    (NULL, 95, 84, 81, 91, 29, 69),
    (NULL, 89, 87, 88, 90, 47, 76),
    (NULL, 67, 87, 94, 87, 65, 78),
    (NULL, 85, 88, 74, 90, 42, 83),
    (NULL, 65, 93, 84, 83, 49, 82),
    (NULL, 70, 82, 89, 89, 67, 66),
    (NULL, 93, 86, 79, 89, 45, 84);


DELETE FROM `Players`;
INSERT INTO
    Players
VALUES (
        NULL,
        "Kylian mbappe",
        91,
        "ST",
        "https://ratings-images-prod.pulse.ea.com/FC25/full/player-portraits/p231747.png?padding=0.7",
        9,
        8,
        NULL,
        1
    ),
    (
        NULL,
        "Rodri",
        91,
        "CDM",
        "https://ratings-images-prod.pulse.ea.com/FC25/full/player-portraits/p231866.png?padding=0.7",
        16,
        11,
        NULL,
        2
    )